export const constants = {
  projectInfo: {
    gitHubURL: "https://github.com/kynefuk/good-first-issue",
  },
  searchFilters: {
    languages: [
      "ActionScript",
      "Arduino",
      "ASP",
      "C",
      "C++",
      "C#",
      "Clojure",
      "ClojureScript",
      "CSS",
      "CoffeeScript",
      "Elm",
      "Elixir",
      "Emacs Lisp",
      "Erlang",
      "Fortran",
      "Go",
      "Groovy",
      "Haskell",
      "HTML",
      "Java",
      "JavaScript",
      "Lisp",
      "Lua",
      "Makefile",
      "Matlab",
      "Objective-C",
      "OCaml",
      "Pascal",
      "Perl",
      "PHP",
      "PowerShell",
      "Puppet",
      "Python",
      "R",
      "Ruby",
      "Rust",
      "Scala",
      "Shell",
      "SQL",
      "Swift",
      "TeX",
      "TypeScript",
      "VimL",
      "Visual Basic",
    ] as const,
    labels: [
      "bug",
      "critical",
      "easy",
      "enhancement",
      "difficulty: easy",
      "difficulty: medium",
      "difficulty: hard",
      "discussion",
      "documentation",
      "feature",
      "first-timers-only",
      "good first issue",
      "hard",
      "help wanted",
      "jump-in",
      "new feature",
      "priority: low",
      "priority: medium",
      "priority: high",
      "prs welcome",
      "question",
      "up for grabs",
      "urgent",
    ] as const,
  },
};
